print()
print("hello World...")
print()
input("What is your name? ")
print()
print("Hello" + " " + "Jenny\n")
print("Hello" + " " + input("What is your name? "))
print()
print("Hey " + input("What is your name? ") + ", " + "how are you? ")
input()
print("Hello " + input("What is your name? "))
print()
